version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'saturday'
      time: '09:00'
      timezone: 'Europe/Berlin'
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'cargo'
    directory: './src-tauri'
    schedule:
      interval: 'monthly'
      day: 'saturday'
      time: '09:00'
      timezone: 'Europe/Berlin'
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
