version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'saturday'
      time: '09:00'
      timezone: 'Europe/Berlin'
    ignore:
      - dependency-type: 'all'
    allow:
      - dependency-type: 'security'

  - package-ecosystem: 'cargo'
    directory: './src-tauri'
    schedule:
      interval: 'monthly'
      day: 'saturday'
      time: '09:00'
      timezone: 'Europe/Berlin'
    ignore:
      - dependency-type: 'all'
    allow:
      - dependency-type: 'security'
