name: Tauri Release

on:
  workflow_call:
    inputs:
      tag_name:
        description: 'The tag name for the release'
        required: true
        type: string
      body:
        description: 'The release body'
        required: true
        type: string
      id:
        description: 'The release ID'
        required: true
        type: string
      draft:
        description: 'Is this a draft release?'
        required: true
        type: boolean
      prerelease:
        description: 'Is this a prerelease?'
        required: true
        type: boolean
      github_token:
        description: 'GitHub token for authentication'
        required: true
        type: string
      tauri_signing_private_key:
        description: 'Tauri signing private key'
        required: true
        type: string
      tauri_signing_private_key_password:
        description: 'Password for Tauri signing private key'
        required: true
        type: string

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: npm install

      - name: Build and Publish Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${ github_token }
          TAURI_SIGNING_PRIVATE_KEY: ${ tauri_signing_private_key }
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${ tauri_signing_private_key_password }
        with:
          tagName: ${{ inputs.tag_name }}
          releaseName: 'App v${{ inputs.tag_name }}'
          releaseBody: ${{ inputs.body }}
          releaseId: ${{ inputs.id }}
          releaseDraft: ${{ inputs.draft }}
          prerelease: ${{ inputs.prerelease }}
          args: ${{ matrix.args }}
