name: Changesets Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Version Packages
        run: npx changeset version

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: npx changeset version
          commit: 'chore(release): version bump and changelog'
          title: 'Release: Version Bump and Changelog'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
