name: Cleanup caches by branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cleanup
        run: |
          set -eo pipefail

          echo "Fetching list of cache keys for PR branch..."
          cacheKeysForPR=$(gh cache list --ref refs/pull/${{ github.event.pull_request.number }}/merge --limit 100 --json id --jq '.[].id')

          if [ -z "$cacheKeysForPR" ]; then
              echo "No cache keys found for the branch. Exiting."
              exit 0
          fi

          echo "Deleting caches..."
          for cacheID in $cacheKeysForPR; do
            gh cache delete "$cacheID"
          done

          echo "Cleanup completed successfully."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
