name: Cleanup caches by branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cleanup
        run: |
          set -eo pipefail

          echo "Fetching list of cache keys for PR branch..."
          cacheKeysForPR=$(gh cache list --ref refs/pull/${{ github.event.pull_request.number }}/merge --limit 100 --json id,createdAt --jq 'sort_by(.createdAt) | .[].id')

          cacheCount=$(echo "$cacheKeysForPR" | wc -l)

          if [ "$cacheCount" -le 2 ]; then
              echo "Only $cacheCount caches found. No cleanup needed."
              exit 0
          fi

          echo "Deleting oldest caches to keep only the newest two..."
          cachesToDelete=$(echo "$cacheKeysForPR" | head -n -2)

          for cacheID in $cachesToDelete; do
            echo "Deleting cache: $cacheID"
            gh cache delete "$cacheID"
          done

          echo "Cleanup completed successfully."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
