name: Semantic Release

on:
  push:
    branches:
      - main
      - next

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Release
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: Set Outputs
        id: set_outputs
        run: |
          echo "tag_name=${{ steps.semantic_release.outputs.tag_name }}" >> $GITHUB_ENV
          echo "body=${{ steps.semantic_release.outputs.body }}" >> $GITHUB_ENV
          echo "id=${{ steps.semantic_release.outputs.id }}" >> $GITHUB_ENV
          echo "draft=${{ steps.semantic_release.outputs.draft }}" >> $GITHUB_ENV
          echo "prerelease=${{ steps.semantic_release.outputs.prerelease }}" >> $GITHUB_ENV

      - name: Log Release Details
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Release URL: $(gh release view --json url --jq '.url')"
          echo "Tag Name: $(gh release view --json tagName --jq '.tagName')"
          echo "Body: $(gh release view --json body --jq '.body')"
          echo "ID: $(gh release view --json id --jq '.id')"
          echo "Draft: $(gh release view --json isDraft --jq '.isDraft')"
          echo "Prerelease: $(gh release view --json isPrerelease --jq '.isPrerelease')"

  # call-tauri:
  #   name: Call Tauri Workflow
  #   runs-on: ubuntu-latest
  #   needs: release

  #   steps:
  #     - name: Call Tauri Workflow
  #       uses: ./.github/workflows/tauri.yml
  #       with:
  #         tag_name: ${{ steps.set_outputs.outputs.tag_name }}
  #         body: ${{ steps.set_outputs.outputs.body }}
  #         id: ${{ steps.set_outputs.outputs.id }}
  #         draft: ${{ steps.set_outputs.outputs.draft }}
  #         prerelease: ${{ steps.set_outputs.outputs.prerelease }}
