name: Semantic Release

on:
  push:
    branches:
      - main
      - next

jobs:
  semantic-release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Release
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Save Release Details
        id: log_release_details
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "tag_name=$(gh release view --json tagName --jq '.tagName')" >> $GITHUB_ENV
          echo "body=$(gh release view --json body --jq '.body')" >> $GITHUB_ENV
          echo "id=$(gh release view --json id --jq '.id')" >> $GITHUB_ENV
          echo "draft=$(gh release view --json isDraft --jq '.isDraft')" >> $GITHUB_ENV
          echo "prerelease=$(gh release view --json isPrerelease --jq '.isPrerelease')" >> $GITHUB_ENV


          echo "Release Details:"
          echo "Tag Name: ${tag_name}"
          echo "Body: ${body}"
          echo "ID: ${id}"
          echo "Draft: ${draft}"
          echo "Prerelease: ${prerelease}"

      - name: Call Tauri Workflow
        id: call_tauri
        uses: ./.github/actions/tauri
        with:
          tag_name: ${{ env.tag_name }}
          id: ${{ env.id }}
          body: ${{ env.body }}
          prerelease: ${{ env.prerelease }}
          draft: ${{ env.draft }}
