name: Semantic Release

on:
  push:
    branches:
      - main
      - next

jobs:
  semantic-release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Release
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Save and Log Release Details
        id: log_release_details
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name=$(gh release view --json tagName --jq '.tagName')
          body=$(gh release view --json body --jq '.body')
          id=$(gh release view --json id --jq '.id')
          draft=$(gh release view --json isDraft --jq '.isDraft')
          prerelease=$(gh release view --json isPrerelease --jq '.isPrerelease')

          echo "Release Details:"
          echo "Tag Name: ${tag_name}"
          echo "Body: ${body}"
          echo "ID: ${id}"
          echo "Draft: ${draft}"
          echo "Prerelease: ${prerelease}"

          echo "tag_name=${tag_name}" > release_info.txt
          echo "id=${id}" >> release_info.txt
          echo "body=${body//$'\n'/\\n}" >> release_info.txt
          echo "prerelease=${prerelease}" >> release_info.txt
          echo "draft=${draft}" >> release_info.txt

      - name: Upload Release Details
        uses: actions/upload-artifact@v4
        with:
          name: release-info
          path: release_info.txt

  tauri-release:
    needs: semantic-release
    runs-on: ubuntu-latest

    steps:
      - name: Download Release Details
        uses: actions/download-artifact@v4
        with:
          name: release-info

      - name: Read Release Details
        run: |
          source release_info.txt
          echo "Tag Name: $tag_name"
          echo "ID: $id"
          echo "Body: $body"
          echo "Draft: $draft"
          echo "Prerelease: $prerelease"

      - name: Call Tauri Action
        uses: ./.github/workflows/tauri.yml
        with:
          tag_name: $tag_name
          id: $id
          body: $body
          prerelease: $prerelease
          draft: $draft
